import { useEffect, useMemo, useState } from "react";
import type { ControlArtifact, ControlJob, ControlRoomAdapter, ControlRoomDetail, ControlTask } from "./types";
import "./control-room.css";

const money = (n: number) => `$${n.toFixed(3)}`;
const time = (n: number) => n ? `${(n / 1000).toFixed(n > 9999 ? 1 : 2)}s` : "—";
const state = (value: string) => value.replaceAll("_", " ");

export function ControlRoom({ adapter, initialJobId }: { adapter: ControlRoomAdapter; initialJobId?: string }) {
  const [jobs, setJobs] = useState<ControlJob[]>([]); const [detail, setDetail] = useState<ControlRoomDetail | null>(null); const [selected, setSelected] = useState(initialJobId ?? "");
  const [filter, setFilter] = useState({ agent: "all", status: "all", task: "" }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState(""); const [editor, setEditor] = useState<ControlArtifact | null>(null);
  const refresh = async (jobId = selected) => { setLoading(true); setError(""); try { const nextJobs = await adapter.listJobs(); setJobs(nextJobs); const nextId = jobId || nextJobs[0]?.id || ""; setSelected(nextId); setDetail(nextId ? await adapter.getJob(nextId) : null); } catch { setError("This run could not be loaded. Check the agency connection and retry."); } finally { setLoading(false); } };
  useEffect(() => { void refresh(initialJobId); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const selectJob = async (id: string) => { setSelected(id); setLoading(true); setDetail(await adapter.getJob(id)); setLoading(false); };
  const metrics = useMemo(() => { const all = detail?.traces ?? []; return { cost: all.reduce((sum, item) => sum + item.costUsd, 0), latency: all.reduce((sum, item) => sum + item.latencyMs, 0), tokens: all.reduce((sum, item) => sum + item.tokenEstimate, 0) }; }, [detail]);
  const visibleTasks = useMemo(() => (detail?.tasks ?? []).filter((task) => (filter.agent === "all" || task.agent === filter.agent) && (filter.status === "all" || task.status === filter.status) && (!filter.task || task.title.toLowerCase().includes(filter.task.toLowerCase()))), [detail, filter]);
  const act = async (key: string, cb: () => Promise<void>) => { setBusy(key); try { await cb(); await refresh(); } catch { setError("That agency action did not complete. No publish state was changed."); } finally { setBusy(null); } };
  return <section className="cr-shell"><header className="cr-topbar"><div><p className="cr-kicker">Calle AI / agency delivery desk</p><h1>Control room</h1></div><div className="cr-live"><i /> {adapter.mode === "demo" ? "Demo data" : "Live Convex"}</div></header>
    {error && <div className="cr-alert" role="alert">{error}<button onClick={() => void refresh()}>Try again</button></div>}
    <div className="cr-layout"><aside className="cr-jobs"><div className="cr-panel-title"><span>Agency jobs</span><button onClick={() => void refresh()}>↻</button></div>{loading && !jobs.length ? <p className="cr-muted">Loading jobs…</p> : jobs.length ? jobs.map((job) => <button key={job.id} className={`cr-job ${selected === job.id ? "selected" : ""}`} onClick={() => void selectJob(job.id)}><span className={`cr-dot ${job.status}`} /><b>{job.businessName}</b><small>{job.category} · {job.city}</small><em>{state(job.status)}</em></button>) : <div className="cr-empty"><b>No agency jobs yet</b><p>Assign a natural-language brief to start a delivery run.</p></div>}</aside>
      <main className="cr-main">{loading && !detail ? <div className="cr-empty large"><b>Reconstructing the run…</b><p>Loading its plan, artifacts, and trace history.</p></div> : detail ? <><section className="cr-summary"><div><p className="cr-kicker">{detail.job.category} · {detail.job.city}</p><h2>{detail.job.businessName}</h2><p>{detail.job.brief}</p></div><span className={`cr-status ${detail.job.status}`}>{state(detail.job.status)}</span></section><section className="cr-metrics"><Metric label="Run cost" value={money(metrics.cost)} /><Metric label="Agent time" value={time(metrics.latency)} /><Metric label="Tokens" value={metrics.tokens.toLocaleString()} /><Metric label="Publish" value={detail.job.publishState} /></section>
        <section className="cr-plan"><div className="cr-section-heading"><div><p className="cr-kicker">Manager plan</p><h3>A tailored agency crew</h3></div><span>{detail.job.managerPlan.length} specialist tasks</span></div><ol>{detail.job.managerPlan.map((step, index) => <li key={`${step.agent}-${index}`}><b>{step.agent}</b><span>{step.task}</span><small>{step.tools.join(" · ")}</small></li>)}</ol></section>
        <section className="cr-filterbar"><input value={filter.task} onChange={(event) => setFilter({ ...filter, task: event.target.value })} placeholder="Find a task" /><select value={filter.agent} onChange={(event) => setFilter({ ...filter, agent: event.target.value })}><option value="all">All agents</option>{[...new Set(detail.tasks.map((task) => task.agent))].map((agent) => <option key={agent}>{agent}</option>)}</select><select value={filter.status} onChange={(event) => setFilter({ ...filter, status: event.target.value })}><option value="all">All task states</option>{[...new Set(detail.tasks.map((task) => task.status))].map((status) => <option key={status}>{state(status)}</option>)}</select></section>
        <section className="cr-trace"><div className="cr-section-heading"><div><p className="cr-kicker">Run trace</p><h3>Who called whom</h3></div><span>{visibleTasks.length} visible</span></div><TraceTree tasks={visibleTasks} artifacts={detail.artifacts} onRetry={(task) => void act(`retry-${task.id}`, () => adapter.retryTask(task.id))} busy={busy} /></section>
        <section className="cr-columns"><div className="cr-artifacts"><div className="cr-section-heading"><div><p className="cr-kicker">Deliverables</p><h3>Artifacts & approvals</h3></div></div>{detail.artifacts.map((artifact) => <ArtifactCard key={artifact.id} artifact={artifact} onApprove={() => void act(`approve-${artifact.id}`, () => adapter.approveArtifact(artifact.id))} onEdit={() => setEditor(artifact)} onRetry={() => artifact.taskId && void act(`retry-${artifact.taskId}`, () => adapter.retryTask(artifact.taskId!))} busy={busy} />)}</div><div className="cr-evidence"><div className="cr-section-heading"><div><p className="cr-kicker">Research</p><h3>Citations used</h3></div></div>{detail.citations.length ? detail.citations.map((citation) => <a className="cr-citation" key={citation.id} href={citation.url} target="_blank" rel="noreferrer"><b>{citation.title} ↗</b><p>{citation.snippet}</p><small>{citation.query}</small></a>) : <p className="cr-muted">No cited research is attached to this run.</p>}</div></section>
        <PublishPanel job={detail.job} siteVersionId={detail.siteVersionId} adapter={adapter} busy={busy} act={act} /></> : <div className="cr-empty large"><b>No selected run</b><p>Choose an agency job to inspect its work.</p></div>}</main></div>
    {editor && <EditArtifact artifact={editor} onClose={() => setEditor(null)} onSave={(note) => void act(`edit-${editor.id}`, async () => { await adapter.requestChanges(editor.id, note); setEditor(null); })} />}</section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><b>{value}</b></div>; }
function TraceTree({ tasks, artifacts, onRetry, busy }: { tasks: ControlTask[]; artifacts: ControlArtifact[]; onRetry: (task: ControlTask) => void; busy: string | null }) { const roots = tasks.filter((task) => !task.parentTaskId); const branch = (task: ControlTask, depth = 0): React.ReactNode => <li key={task.id} style={{ "--depth": depth } as React.CSSProperties}><article className={`cr-task ${task.status}`}><div className="cr-task-title"><span className="cr-dot" /><div><b>{task.agent}</b><p>{task.title}</p></div><em>{state(task.status)}</em></div><div className="cr-task-grid"><span><small>Input</small>{task.inputSummary}</span><span><small>Output</small>{task.outputSummary}</span><span><small>Tools</small>{task.tools.join(", ") || "—"}</span><span><small>Latency / cost</small>{time(task.latencyMs)} · {money(task.costUsd)} · {task.tokenEstimate} tok</span></div>{task.status === "needs_review" || task.status === "failed" ? <button className="cr-button ghost" disabled={busy === `retry-${task.id}`} onClick={() => onRetry(task)}>{busy === `retry-${task.id}` ? "Queuing…" : "Retry only this task"}</button> : null}{artifacts.filter((artifact) => artifact.taskId === task.id).map((artifact) => <small className="cr-task-artifact" key={artifact.id}>↳ {artifact.title} · v{artifact.version}</small>)}</article><ul>{tasks.filter((child) => child.parentTaskId === task.id).map((child) => branch(child, depth + 1))}</ul></li>; return <ul className="cr-tree">{roots.map((task) => branch(task))}</ul>; }
function ArtifactCard({ artifact, onApprove, onEdit, onRetry, busy }: { artifact: ControlArtifact; onApprove: () => void; onEdit: () => void; onRetry: () => void; busy: string | null }) { const payload = JSON.stringify(artifact.payload, null, 2); return <article className={`cr-artifact ${artifact.approvalStatus}`}><div><span className={`cr-status ${artifact.approvalStatus}`}>{state(artifact.approvalStatus)}</span><small>v{artifact.version} · {Math.round(artifact.confidence * 100)}% confidence</small></div><h4>{artifact.title}</h4><pre>{payload}</pre><div className="cr-actions">{artifact.approvalStatus !== "approved" && <button className="cr-button" disabled={busy === `approve-${artifact.id}`} onClick={onApprove}>Approve</button>}<button className="cr-button ghost" onClick={onEdit}>Request edit</button>{artifact.approvalStatus === "escalated" && <button className="cr-button ghost" onClick={onRetry}>Correct & retry</button>}</div></article>; }
function PublishPanel({ job, siteVersionId, adapter, busy, act }: { job: ControlJob; siteVersionId?: string; adapter: ControlRoomAdapter; busy: string | null; act: (key: string, cb: () => Promise<void>) => void }) { const published = job.publishState === "published"; return <section className="cr-publish"><div><p className="cr-kicker">Public delivery</p><h3>{published ? "This storefront is live" : "Ready when reviewed"}</h3><p>{published ? "The approved site version is available on the public route." : "Publishing stays blocked until flagged facts are reviewed."}</p></div><div className="cr-publish-actions">{published && job.publishedUrl && <a className="cr-button ghost" href={job.publishedUrl} target="_blank" rel="noreferrer">Preview public site ↗</a>}{published && adapter.unpublish ? <button className="cr-button ghost" onClick={() => act("unpublish", () => adapter.unpublish!(job))}>Unpublish</button> : <button className="cr-button" disabled={busy === "publish"} onClick={() => act("publish", () => adapter.publish(job, siteVersionId))}>{busy === "publish" ? "Publishing…" : "Publish approved site"}</button>}</div></section>; }
function EditArtifact({ artifact, onClose, onSave }: { artifact: ControlArtifact; onClose: () => void; onSave: (note: string) => void }) { const [note, setNote] = useState("Please verify the unreadable price against the original menu before republishing."); return <div className="cr-modal-backdrop" role="dialog" aria-modal="true"><form className="cr-modal" onSubmit={(event) => { event.preventDefault(); onSave(note); }}><p className="cr-kicker">Revision request · {artifact.title}</p><h3>Send this artifact back with context</h3><textarea value={note} onChange={(event) => setNote(event.target.value)} /><div><button type="button" className="cr-button ghost" onClick={onClose}>Cancel</button><button className="cr-button" type="submit">Request targeted revision</button></div></form></div>; }
