import type { ControlArtifact, ControlCitation, ControlJob, ControlRoomAdapter, ControlRoomDetail, ControlTask, ControlTrace } from "./types";

const stamp = Date.now() - 1000 * 60 * 18;
const manager: ControlTask = { id: "task-manager", agent: "Agency Manager", title: "Plan, delegate, and review local-presence job", status: "complete", tools: ["planner", "agency-memory"], inputSummary: "Spanish-first Yucatán menu + Mission District presence brief", outputSummary: "Created a five-specialist plan with a cultural-preservation guardrail.", latencyMs: 320, tokenEstimate: 410, costUsd: .006 };
const tasks: ControlTask[] = [manager,
  { id: "task-intake", parentTaskId: manager.id, agent: "Intake & Evidence", title: "Build evidence ledger and canonical fact sheet", status: "complete", tools: ["source-parser"], inputSummary: "Brief, Maps URL, menu photos", outputSummary: "Canonical facts and fields needing owner verification.", latencyMs: 450, tokenEstimate: 260, costUsd: .004 },
  { id: "task-menu", parentTaskId: manager.id, agent: "Menu Structuring", title: "Extract categories, names, prices, and uncertainty", status: "needs_review", tools: ["vision-ocr"], inputSummary: "Fact sheet + photographed Spanish menu", outputSummary: "Structured menu; one price is unreadable.", latencyMs: 540, tokenEstimate: 305, costUsd: .006 },
  { id: "task-localize", parentTaskId: manager.id, agent: "Cultural Localization", title: "Create bilingual, culturally respectful customer content", status: "complete", tools: ["localization-model", "agency-policy"], inputSummary: "Structured menu handoff", outputSummary: "Spanish names preserved with newcomer-friendly English explanations.", latencyMs: 630, tokenEstimate: 350, costUsd: .008 },
  { id: "task-research", parentTaskId: manager.id, agent: "Local Discovery Research", title: "Research regional context with attributable sources", status: "complete", tools: ["linkup"], inputSummary: "Yucatán culinary context query", outputSummary: "Cited regional context for listing and menu explanations.", latencyMs: 720, tokenEstimate: 395, costUsd: .01 },
  { id: "task-publish", parentTaskId: manager.id, agent: "Publisher & QA", title: "Assemble microsite and local-presence pack", status: "queued", tools: ["site-renderer", "required-field-validator"], inputSummary: "Approved specialist artifacts", outputSummary: "Waiting for the flagged menu field to be resolved.", latencyMs: 0, tokenEstimate: 0, costUsd: 0 },
];
const artifacts: ControlArtifact[] = [
  { id: "artifact-evidence", taskId: "task-intake", kind: "evidence_ledger", title: "Canonical fact sheet & evidence ledger", payload: { verified: ["Business name", "Mission District", "Spanish-first menu"], needsOwnerReview: ["Hours", "Phone", "Current menu prices"] }, confidence: .92, approvalStatus: "pending", version: 1, createdAt: stamp },
  { id: "artifact-catalog", taskId: "task-menu", kind: "structured_catalog", title: "Structured Spanish-first menu", payload: { items: [{ name: "Cochinita Pibil", price: "Needs owner verification", confidence: .74 }, { name: "Panuchos", price: "Needs owner verification", confidence: .89 }] }, confidence: .81, approvalStatus: "escalated", version: 2, createdAt: stamp + 1 },
  { id: "artifact-copy", taskId: "task-localize", kind: "localization_copy", title: "Culturally informed bilingual copy", payload: { es: "Relleno Negro", en: "Traditional Yucatán turkey stew flavored with roasted chiles, served with a pork-and-egg filling.", rationale: "Preserves the regional name and explains, rather than flattens, the dish." }, confidence: .91, approvalStatus: "pending", version: 1, createdAt: stamp + 2 },
  { id: "artifact-research", taskId: "task-research", kind: "research_pack", title: "Source-backed discovery research", payload: { query: "Yucatán cuisine regional terms", findings: ["Keep original dish names in Spanish and provide contextual English explanations."] }, confidence: .89, approvalStatus: "pending", version: 1, createdAt: stamp + 3 },
  { id: "artifact-site", taskId: "task-publish", kind: "published_site_candidate", title: "Published microsite candidate", payload: { route: "/b/yucatasia", status: "blocked by menu review" }, confidence: .93, approvalStatus: "pending", version: 1, createdAt: stamp + 4 },
];
const traces: ControlTrace[] = tasks.map((task, i) => ({ id: `trace-${task.id}`, taskId: task.id, parentTaskId: task.parentTaskId, agent: task.agent, event: task.status === "needs_review" ? "escalated" : task.status === "queued" ? "waiting" : "completed", summary: task.outputSummary, inputSummary: task.inputSummary, outputSummary: task.outputSummary, tools: task.tools, latencyMs: task.latencyMs, tokenEstimate: task.tokenEstimate, costUsd: task.costUsd, createdAt: stamp + i }));
const citations: ControlCitation[] = [{ id: "citation-yucatan", artifactId: "artifact-research", title: "Yucatán cuisine context", url: "https://example.com/yucatan-cuisine", snippet: "Demo citation. In production this is a persisted Linkup result.", query: "Yucatán cuisine regional terms", retrievedAt: stamp + 3 }];
const baseJob: ControlJob = { id: "demo-yucatasia", businessId: "business-yucatasia", businessName: "Yucatasia", category: "Restaurant", city: "San Francisco", status: "needs_review", brief: "Create a Spanish-first bilingual local-presence site for Yucatasia. Preserve regional Yucatán dish names and explain them clearly for newcomers.", managerPlan: tasks.slice(1).map(({ agent, title, tools }) => ({ agent, task: title, tools })), publishState: "draft", createdAt: stamp, updatedAt: stamp + 4 };
let jobs: ControlJob[] = [baseJob, { ...baseJob, id: "demo-chelys", businessId: "business-chelys", businessName: "Chely’s Beauty Salon", category: "Beauty salon", city: "San Francisco", status: "published", publishState: "published", publishedUrl: "/b/chelys-beauty-salon", updatedAt: stamp - 2 * 86400000 }, { ...baseJob, id: "demo-bakery", businessId: "business-bakery", businessName: "La Estrella Bakery", category: "Bakery", city: "San Francisco", status: "failed", publishState: "draft", updatedAt: stamp - 86400000 }];
let detail: ControlRoomDetail = { job: baseJob, tasks, artifacts, traces, citations, siteVersionId: "site-yucatasia-v1" };

export const mockControlRoomAdapter: ControlRoomAdapter = {
  mode: "demo",
  async listJobs() { return [...jobs]; },
  async getJob(id) { if (id !== baseJob.id) return { ...detail, job: jobs.find((job) => job.id === id) ?? baseJob }; return { ...detail, job: jobs[0] }; },
  async approveArtifact(id) { const item = detail.artifacts.find((artifact) => artifact.id === id); if (item) item.approvalStatus = "approved"; },
  async requestChanges(id) { const item = detail.artifacts.find((artifact) => artifact.id === id); if (item) item.approvalStatus = "changes_requested"; },
  async retryTask(id) { const task = detail.tasks.find((current) => current.id === id); if (task) { task.status = "queued"; detail.traces.unshift({ id: `retry-${Date.now()}`, taskId: id, parentTaskId: task.parentTaskId, agent: task.agent, event: "retry_requested", summary: "Task returned to queue for targeted re-run.", inputSummary: "Operator corrected a low-confidence field", outputSummary: "Task returned to queue for targeted re-run.", tools: [], latencyMs: 0, tokenEstimate: 0, costUsd: 0, createdAt: Date.now() }); } },
  async publish(job) { jobs = jobs.map((current) => current.id === job.id ? { ...current, status: "published", publishState: "published", publishedUrl: `/b/${current.businessName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}` } : current); },
  async unpublish(job) { jobs = jobs.map((current) => current.id === job.id ? { ...current, publishState: "unpublished", status: "needs_review", publishedUrl: undefined } : current); },
};
